# suppress inspection "UnusedProperty" for whole file
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.1.1
minecraft_version_code=26.1.1
loader_version=0.18.4
fabric_version=0.144.1+26.1

# Mod Properties
mod_version=14.2
maven_group=com.redlimerl.speedrunigt
archives_base_name=SpeedRunIGT
